### ISSUE TITLE
我的Atom插件

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#131]
## 自定义工具条

- tool-bar
- flex-tool-bar

## Markdown 插件

- markdown-preview-enhanced
- language-markdown
- markdown-table-editor
- markdown-writer
- tool-bar-markdown-writer

## 快速替换

- toggle-quotes
- toggler

## minimap

- minimap
- minimap-find-and-replace
- minimap-git-diff
- minimap-highlight-selected
- minimap-selection
- minimap-pigments
- minimap-linter
- minimap-cursorline

## 自动补全

- autocomplete-json
- autocomplete-paths

## 颜色

- color-picker
- pigments

## 代码块

- css-snippets
- javascript-snippets
- es6-javascript

## react

- react-es6-snippets
- react-snippets
- language-babel
- react-native-snippets-youngjuning
- language-groovy
- language-gradle
- language-generic-config
- language-batch
- language-postcss

## 构建工具

- atom-yarn
- script
- px2rem-plus

## emmet

- emmet
- emmet-snippets-compatibility
- emmet-jsx-props

## 注释

- sublime-block-comment
- docblockr

## 美化&辅助

- file-icons
- filesize
- fonts
- pdf-view
- simple-drag-drop-text
- simple-chinese-menu

## 高亮

- highlight-line
- highlight-selected

## hyperclick

- hyperclick
- js-hyperclick
- vue-hyperclick

## 代码格式化

- pretty-json

## 语言支持

- language-apache
-  language-ejs
- language-ini
- language-vuejs
- language-nginx

## VSC

- git-plus
- tree-view-git-status
- split-diff

## IDE

- atom-ide-ui
- atom-ide-debugger-node
- ide-html
- ide-css
- ide-json
- ide-typescript

**Comment by youngjuning** [comment]
## npm

- atom-npm：`npm install`、`npm update`、`npm run <script>`

**Comment by youngjunning** [comment]
- hyperlink-hyperclick

**Comment by youngjunning** [comment]
## 我的插件

- atom-elementui
- atom-iviewui
- atom-leancloud
- languge-wx
- language-vuejs
- react-native-snippets-youngjuning
- bootcdn-snippets
