### ISSUE TITLE
Mock入门指北

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#189]
### 1.1 前后端分离

前后端分离后, 大家从此进入了所谓的并行开发时代. 一旦完成前后端的(边界)分工, 大家就可以各司其职了。

前端在与后端交互时, 要想有效地提高工作效率, 后端的接口文档就是重中之重了。

### 1.2 只有接口文档不如没有

所谓的接口文档, 即一份数据的契约书. 前端的所有逻辑和展现全部依赖接口文档中规定的数据结构。

但是光有接口文档不足以提升前端的开发效率, 因为前端开发时, 必须调用实实在在的接口和数据才能看到结果, 尽早跑通所有的前端流程, 这才是效率的根本。

对于后端来说手动维护接口文档，短期内对项目的推进弊大于利，甚至会拖慢进度。

在前后端并行开发的时代, 前端开发时, 后端也才开发, 接口还没有开发完, 后端拿什么给前端调用。

那么问题来了, 我们怎么做一份能够调用的接口文档呢?

### 1.3 假数据时代

前端不可以傻傻地等后端接口开发完, 才开始做前端的逻辑, 因此我们习惯了做假的接口数据, 让前端工作可以顺利地进行下去, 加快开发进度。

#### 原始的静态数据文件

例如将 **mock-data.json** 放在项目的根目录, 直接通过 ajax 调用即可。

**这种方式弊端很大：**

如果项目的接口较少维护起来还比较容易，但是一旦涉及到数十个接口的调用，我们就需要在项目里写新建许多个`json` 文件，如果恰好后端接口的路径又比较长的话，那项目目录将会十分的混乱。就算文件很少，那么文件里面就几条死的数据, 肯定做不到随机变化. 假如前端需要看 100 条数据的结果呢? **你是复制粘帖 100 次吗?**

除此之外，通常情况下接口并不一定就会以 `json` 结尾（后端同学也许并不会听你解释。。）
 如果按照RESTFUL的格式书写，比如`"api/zoos/animals"`，那么我们需要准备书写两套调用接口代码，一种以json格式结尾作为本地mock，另一套才是线上接口代码,每次build构建代码时，一定得记得将调用接口的地方改为线上代码。**这种做法效率太低了!!!**

#### Mock.js

因为 Mock.js 可以拦截前端的 ajax 请求, 因此我只要在开发时按照接口文档给出的接口和数据, 让 Mock.js 去拦截接口并提供随机的假数据即可, 例如实现一个开发时用的 `mock-api.js`。

**这种方式弊端也不小：**

当后端接口开发完成后, 去掉 `mock-api.js`, 即可切换到后端接口, 前端代码不需要做任何修改。

在前端使用 **Mock.js** 是可以造出一个"假的接口", 还可以配置出随机数据, 但毕竟不是真正的后端接口, 还需要在前端引用一段定义假接口的代码(例如 `mock-api.js`), 势必会造成管理上的问题. 想一想如果有 20, 30 个页面都要引用了 `mock-api.js`, 后端接口完成后, 你千万得记得将 `mock-api.js`从这些页面中去掉, 是不是觉得有点累赘, 不够智能啊。

看来是时候自己写一个 mock server 来提供假接口假数据了, 为前端提供像模像样的假后端接口。

### 1.4 mock server 才是未来

**什么是Mock Server ?**

专门实现 mock 功能的一个服务。

**Mock Server的作用？**

现今的业务系统很少有孤立存在的，它们或多或少需要使用兄弟团队或是其他公司提供的服务，这给我们的联调和测试造成了麻烦。对于这种情况，我们常见的解决方案是搭建一个临时的server，模拟那些服务，提供数据进行联调和测试。这就是 mock server 出现原因。

下图很好的解释了Mock Server 位置和作用：

![](https://images2017.cnblogs.com/blog/311516/201709/311516-20170912180553860-879452344.png)

**Comment by youngjunning** [comment]
## 二、mock库

- nuysoft/Mock [![GitHub stars](https://img.shields.io/github/stars/nuysoft/Mock.svg?style=social&label=Stars)](https://github.com/nuysoft/Mock)：生成随机数据，拦截 Ajax 请求

- marak/Faker.js [![GitHub stars](https://img.shields.io/github/stars/marak/Faker.js.svg?style=social&label=Stars)](https://github.com/marak/Faker.js/)：在Node.js和浏览器中生成大量真实的假数据

- sinonjs/sinon [![GitHub stars](https://img.shields.io/github/stars/sinonjs/sinon.svg?style=social&label=Stars)](https://github.com/sinonjs/sinon)：测试JavaScript的间谍，存根和模拟

**Comment by youngjunning** [comment]
### 三、API 描述语言规范

### 3.1 swagger [![GitHub stars](https://img.shields.io/github/stars/swagger-api/swagger-ui.svg?style=social&label=Stars)](https://github.com/swagger-api/swagger-ui)

Swagger是一种Rest API的 简单但强大的表示方式，标准的，语言无关，这种 表示方式不但人可读，而且机器可读。 可以作为Rest API的交互式文档，也可以作为Rest API的形式化的接口描述，生成客户端和服务端的代码。 

**为什么用swagger**

- 生态良好
- 维护度高
- 对前后端都友好
- 易于推广

**配套工具**

- Swagger API Spec：描述Rest API的语言
- swagger-ui [![GitHub stars](https://img.shields.io/github/stars/swagger-api/swagger-ui.svg?style=social&label=Stars)](https://github.com/swagger-api/swagger-ui)：将Swagger API Spec以HTML页面展现出来的模块
- swagger-editor [![GitHub stars](https://img.shields.io/github/stars/swagger-api/swagger-editor.svg?style=social&label=Stars)](https://github.com/swagger-api/swagger-editor)：Swagger API Spec的编辑器

**参考资源**

- [如何编写基于OpenAPI规范的API文档](http://t.cn/RXThJQu)
- [基于 Swagger 的前后端分离开发实践](http://t.cn/E2RZxow)
- [Swagger：Rest API的描述语言](https://zhuanlan.zhihu.com/p/21353795)

### 3.2 api-blueprint  [![GitHub stars](https://img.shields.io/github/stars/apiaryio/api-blueprint.svg?style=social&label=Stars)](https://github.com/apiaryio/api-blueprint)

如果你正在使用 markdown 来编写 api 文档的话，API Blueprint 一定会成为你的更好的选择。

API Blueprint 是一套基于 markdown 的 API 描述语言规范，如果你按照它的规范来编写你的 API 文档的话，你就可以享受到配套的工具服务了。

**为什么不用api-blueprint**

- 维护度不高
- 后台不够强大

**配套工具**

- drakov [![GitHub stars](https://img.shields.io/github/stars/Aconex/drakov.svg?style=social&label=Stars)](https://github.com/Aconex/drakov)：实现 `api-blueprint` 规范的 Mock Server
- aglio [![GitHub stars](https://img.shields.io/github/stars/danielgtaylor/aglio.svg?style=social&label=Stars)](https://github.com/danielgtaylor/aglio)：一个将`api-blueprint`渲染成静态HTML的工具

**参考资源**

- [使用 API-Blueprint 编写 API 文档](http://t.cn/E2QD4Gr)

**Comment by youngjunning** [comment]
## 四、Mock Server

### 4.1 easy-mock[![GitHub stars](https://img.shields.io/github/stars/easy-mock/easy-mock.svg?style=social&label=Stars)](https://github.com/easy-mock/easy-mock)

Easy Mock 是一个可视化，并且能快速生成**模拟数据**的持久化服务。支持中文文档，基于 **Node.js**、**MongoDB**、**Redis** 搭建。

**特性**

- 支持接口代理
- 支持快捷键操作
- 支持协同编辑
- 支持团队项目
- 支持 RESTful
- 支持 [Swagger](https://swagger.io) | OpenAPI Specification ([1.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md) & [2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) & [3.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md))
  - 基于 Swagger 快速创建项目
  - 支持显示接口入参与返回值
  - 支持显示实体类
- 支持灵活性与扩展性更高的响应式数据开发
- 支持自定义响应配置（例：status/headers/cookies）
- 支持 [Mock.js](http://mockjs.com/) 语法
- 支持 [restc](https://github.com/ElemeFE/restc) 方式的接口预览
- **支持docker部署**

### 4.2 rap2-delos [![GitHub stars](https://img.shields.io/github/stars/thx/rap2-delos.svg?style=social&label=Stars)](https://github.com/thx/rap2-delos)

> RAP[![GitHub stars](https://img.shields.io/github/stars/thx/RAP.svg?style=social&label=Stars)](https://github.com/thx/RAP)

阿里妈妈MUX团队出品！阿里巴巴都在用！1000+公司的选择！阿里妈妈前端团队出品的开源接口管理工具RAP第二代[http://rap2.taobao.org](http://rap2.taobao.org/)

RAP通过GUI工具帮助**WEB工程师**更高效的管理接口文档，同时通过分析接口结构自动生成Mock数据、校验真实接口的正确性，使接口文档成为开发流程中的强依赖。有了结构化的API数据，RAP可以做的更多，而我们可以避免更多重复劳动。

![img](https://camo.githubusercontent.com/e37481e2ed001654ab426d5a489d8c5fbdb893f0/687474703a2f2f67746d7330342e616c6963646e2e636f6d2f7470732f69342f544231397467554b565858585858415858585841684342355658582d313232322d3634362e706e67)

**特性**

- Web接口管理工具
- 开源免费
- 接口自动化
- MOCK数据自动生成
- 自动化测试
- 企业级管理
- **支持docker部署**

### 4.4 yapi [![GitHub stars](https://img.shields.io/github/stars/YMFE/yapi.svg?style=social&label=Stars)](https://github.com/YMFE/yapi)

YApi 是高效、易用、功能强大的 api 管理平台，旨在为开发、产品、测试人员提供更优雅的接口管理服务。可以帮助开发者轻松创建、发布、维护 API，YApi 还为用户提供了优秀的交互体验，开发人员只需利用平台提供的接口数据写入工具以及简单的点击操作就可以实现接口的管理。

#### 特性

- 基于 Json5 和 Mockjs 定义接口返回数据的结构和文档，效率提升多倍
- 扁平化权限设计，即保证了大型企业级项目的管理，又保证了易用性
- 类似 postman 的接口调试
- 自动化测试, 支持对 Response 断言
- MockServer 除支持普通的随机 mock 外，还增加了 Mock 期望功能，根据设置的请求过滤规则，返回期望数据
- 支持 postman, har, swagger 数据导入
- 免费开源，内网部署，信息再也不怕泄露了

### 4.3 其他

- mockserver [![GitHub stars](https://img.shields.io/github/stars/jamesdbloom/mockserver.svg?style=social&label=Stars)](https://github.com/jamesdbloom/mockserver) MockServer可以轻松模拟您通过HTTP或HTTPS与使用Java，JavaScript和Ruby编写的客户端集成的任何系统
- TommyLemon/APIJSON[![GitHub stars](https://img.shields.io/github/stars/TommyLemon/APIJSON.svg?style=social&label=Stars)](https://github.com/TommyLemon/APIJSON) 🚀后端接口和文档自动化，前端(客户端) 定制返回JSON的数据和结构！
- json-server[![GitHub stars](https://img.shields.io/github/stars/typicode/json-server.svg?style=social&label=Stars)](https://github.com/typicode/json-server)：在不到30秒的时间内获得零编码的完整虚假REST API
- service-mocker[![GitHub stars](https://img.shields.io/github/stars/service-mocker/service-mocker.svg?style=social&label=Stars)](https://github.com/service-mocker/service-mocker)
- wiremock[![GitHub stars](https://img.shields.io/github/stars/tomakehurst/wiremock.svg?style=social&label=Stars)](https://github.com/tomakehurst/wiremock)

**Comment by youngjunning** [comment]
## 五、预选方案

### 5.1 rap2-delos [![GitHub stars](https://img.shields.io/github/stars/thx/rap2-delos.svg?style=social&label=Stars)](https://github.com/thx/rap2-delos) 

> 其实这个库第一个版本RAP[![GitHub stars](https://img.shields.io/github/stars/thx/RAP.svg?style=social&label=Stars)](https://github.com/thx/RAP) 9k 的星星。阿里的库总喜欢迁移库
>
> 官方测试地址：http://rap2.taobao.org/

#### 参考资源

- [官方文档](https://github.com/thx/rap2-delos/wiki)

- [RAP2搭建教程(mock服务)](http://www.195440.com/?p=586)
- [教你使用docker部署淘宝rap2镜像](http://t.cn/E2RfWcE)
- [RAP2：使用docker镜像进行构建，启动部署](http://t.cn/E2RfspZ)

### 5.2 easy-mock [![GitHub stars](https://img.shields.io/github/stars/easy-mock/easy-mock.svg?style=social&label=Stars)](https://github.com/easy-mock/easy-mock)

> 官方测试地址：https://easy-mock.com/

#### 参考资源

- [官方文档](https://easy-mock.com/)
- [easy-mock-docker](https://github.com/easy-mock/easy-mock-docker)
- [活儿好又性感的 Mock 平台 - Easy Mock](http://t.cn/RXTUaVe)
- [easy-mock简单使用](http://t.cn/E2RNdzt)

### 5.3 yapi [![GitHub stars](https://img.shields.io/github/stars/YMFE/yapi.svg?style=social&label=Stars)](https://github.com/YMFE/yapi) 去哪开发

#### 参考资源

- [官方文档](https://yapi.ymfe.org/index.html)
- [anoy/yapi](http://t.cn/ELt0NmL):使用 Docker 构建 Yapi(麻烦，没有使用docker-compose)
- [branchzero/yapi](https://hub.docker.com/r/branchzero/yapi/):yapi docker for https://github.com/YMFE/yapi (使用docker-compose管理)
- [顶尖 API 文档管理工具 (Yapi)](https://www.jianshu.com/p/a97d2efb23c5)
- [阿里容器镜像服务](https://dev.aliyun.com/)：高性能的本地Registry，提供上传、下载、构建及托管的全方位镜像服务

**Comment by youngjunning** [comment]
### 参考资源

- [为什么你需要一个 mock server](http://t.cn/E28OwOR)
- [构建前端Mock Server的利器/Json-Server](http://t.cn/E28WguJ)
- [美团Mock Server实践](http://t.cn/RkfkKQO)
- [Mock Server 入门](http://t.cn/E28YAVW)
- [前后端10大痛点解析](http://t.cn/E28Q3xw)
- [你是如何构建 Web 前端 Mock Server 的？](http://t.cn/RoR5xKX)
- [API 设计: RAML、Swagger、Blueprint三者的比较](https://www.cnblogs.com/softidea/p/5728952.html)
- [Swagger：Rest API的描述语言](https://zhuanlan.zhihu.com/p/21353795)
- [RAP2搭建教程(mock服务)](http://www.195440.com/?p=586)
- [教你使用docker部署淘宝rap2镜像](http://t.cn/E2RfWcE)
- [RAP2：使用docker镜像进行构建，启动部署](http://t.cn/E2RfspZ)

**Comment by youngjuning** [comment]
## rap2-delos实施

**Comment by youngjuning** [comment]
## easy-mock 实施

**Comment by youngjuning** [comment]
## rap2-delos windows

### 安装依赖

- 安装 redis

**Comment by youngjuning** [comment]
## easy-mock 实施

**Comment by youngjunning** [comment]
#191

**Comment by youngjunning** [comment]
## 杂文

- [利用mock提高效率](https://www.cnblogs.com/dreamless/p/8487322.html)
