### ISSUE TITLE
阿里开源mock系统 rap2 指北

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#191]
RAP2是在RAP1基础上重做的新项目，它包含两个组件(对应两个Github Repository)。

- rap2-delos [![GitHub stars](https://img.shields.io/github/stars/thx/rap2-delos.svg?style=social&label=Stars)](https://github.com/thx/rap2-delos)：后端数据API服务器，基于Koa + MySQL
- rap2-dolores[![GitHub stars](https://img.shields.io/github/stars/thx/rap2-dolores.svg?style=social&label=Stars)](https://github.com/thx/rap2-dolores): 前端静态资源，基于React

## 什么是 rap2

RAP通过GUI工具帮助WEB工程师更高效的管理接口文档，同时通过分析接口结构自动生成Mock数据、校验真实接口的正确性，使接口文档成为开发流程中的强依赖。有了结构化的API数据，RAP可以做的更多，而我们可以避免更多重复劳动。

![image](https://user-images.githubusercontent.com/13204332/48930343-d968f780-ef2a-11e8-9ed4-7de2064d7669.png)

上面是摘自https://github.com/thx/RAP淘宝阿里妈妈对rap1的描述，看了图一下子就能明白，后端制定API返回数据格式，前端通过接口地址在线mock，避免了前后端因为进度不一致而出现单方面等待的现象。

## 体验

可以直接使用淘宝提供的[在线服务](http://rap2.taobao.org/)来生成在线的接口地址，通过申请一个账号后，即可在里面进行接口的编写、测试等等…这里不再赘述。

**Comment by youngjunning** [comment]
# 非docker部署

## 一、服务端 delos 环境搭建

### 1.1 环境要求与配置

- [Node.js 8.9.4+](https://nodejs.org/zh-cn/)
  - [NodeJS环境维护](http://t.cn/EwjGwYE)
- [MySQL 5.7+](https://pan.baidu.com/s/1YDupuNpcQht5QVqC-RCb2A)
  - [MySQL on Windows](https://dev.mysql.com/downloads/windows/)
- [Redis 4.0+](https://github.com/antirez/redis)
  - [Redis 安装](http://t.cn/RnWsuY1)
  - [Windows环境下的Redis安装与配置](http://t.cn/RraQttT)

### 1.2 获取代码

```
git clone https://github.com/thx/rap2-delos.git
```

### 1.3 初始化

```bash
$ npm install # 项目根目录
```

### 1.4 安装守护进程 pm2

```bash
$ npm install -g pm2
```

### 1.5 启动redis-server

> 注意：开发模式需要启动 `redis-server`

后台执行可以使用 `nohup` 或 `pm2`，这里推荐使用 `pm2`，下面命令会安装 `pm2`，并通过`pm2`来启动`redis`缓存服务: `$ npm run start:redis`（项目根目录下执行）

### 1.6 创建数据库

- Windows
   ```bash
   $ CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
   ```
- Mac or Linux
   ```bash
   $ mysql -e 'CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci';
   ```

### 1.7 配置文件

> config.dev.ts`其中dev，表示开发环境，其他同理

修改 `rap2-delos/src/config/config.dev.ts`文件中`db`对象中`username`，`password`参数与**本地**或者**开发环境**的数据库信息匹配。

### 1.8 安装 TypeScript 编译包

```bash
$ npm install -g typescript
```

### 1.9 TypeScript编译项目

```bash
$ npm run build # 项目根目录
```

### 1.10 初始化数据库

```bash
$ npm run create-db # 项目根目录
```

### 1.11 执行mocha测试用例和js代码规范检查

```bash
$ npm run check
```

### 1.12 启动项目

#### 开发模式

启动开发模式的服务器 监视并在发生代码变更时自动重启

```bash
$ npm run dev
```

#### 生产模式

启动生产模式服务器

```bash
npm start
```

看到浏览器中如下提示，表示**服务端delos**已经部署成功

> RAP2后端服务已启动，请从前端服务(rap2-dolores)访问。 RAP2 back-end server is started, please visit via front-end service (rap2-dolores).

### 1.13 常见问题

##### 1、Windows下执行`npm run build`，提示`'rm' 不是内部或外部命令，也不是可运行的程序或批处理文件`   

- 原因：`rm` 是Linux下命令，
- 解决方法：Windows系统可使用 `git bash` 或 `powershell` 打开该项目，执行该命令

##### 2、执行`npm run create-db`命令，提示`Unable to connect to the database:{ SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password:NO)}`

- 原因：未修改`rap2-delos/src/config`目录下数据库配置文件，或者是与文件中的数据库信息与之连接的数据库信息不匹配
- 解决方法：修改`config.dev.ts`文件数据库配置信息

> 如果修改正确无误后，执行`npm run create-db`依旧出错，那么查看该项目中是否已经存在`dist`目录，如果有，请按照如上修改对应的数据库配置信息

##### 3、执行`npm run dev`命令，提示`Error: listen EADDRINUSE :::8080`

- 原因：8080 端口被占用
- 解决方法：杀掉占用 8080 端口的应用

##### 4、执行`npm install` 命令，提示`hiredis` 编译无法通过

原因：无权限操作 `rap2-delos/node_modules/hiredis`路径

解决方法：`sudo npm install`

> 如果提示`sudo: npm: command not found`，请参考 [stackoverflow-npm](https://stackoverflow.com/questions/31472755/sudo-npm-command-not-found),[stackoverflow-node](https://stackoverflow.com/questions/4976658/on-ec2-sudo-node-command-not-found-but-node-without-sudo-is-ok)

##### 5、执行`npm run dev`可以正常启动，`npm start`命令无法正常启动服务

- 原因：请使用`pm2 logs`查看日志具体定位

- 示例：由于 Redis 的安全模式，不能正常使用

  ```
  ReplyError: Ready check failed: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 
  
  1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 
  2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 
  3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 
  4) Setup a bind address or an authentication password. 
  NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
  ```

- 解决方法： 使用`--protected-mode no`方式启动

## 二、客户端 dolores 环境搭建

### 2.1、获取源代码

```bash
$ git clone https://github.com/thx/rap2-dolores.git
```

### 2.2、安装项目依赖包

```bash
$ npm install # 项目根目录
```

### 2.3、环境配置

修改`rap2-dolores/src/config/config.dev.ts`文件，`serve`地址是 **服务端** `rap2-delos` 部署成功后的地址，默认：`'http://localhost:8080'`

### 2.3、启动项目

#### 开发模式

自动监视改变后重新编译

```bash
$ npm run dev
```

#### 测试用例

```bash
$ npm run test
```

#### 生产模式

编译 React 生产包

```bash
$ npm run build
```

用 serve 命令或 nginx 服务器路由到编译产出的 build 文件夹作为静态服务器即可

```bash
serve -s ./build -p 7070
```

看到浏览器中出现登录页面，表示部署成功

![](https://res.cloudinary.com/incoder/image/upload/v1525517454/blog/gitpages-rap2-dolores-success.png)

### 2.4 常见问题

#### 部署问题

##### 1、执行`npm run dev`，提示

```bash
return process.dlopen(module,path._makeLong(filename))
...
...node_modules\node-sass\vendor\win32-x64-57\binding.node is not a valid Win32 application...
```

- 原因：项目依赖包`node-sass`没有安装完全
- 解决方法：`npm install node-sass`

##### 2、项目运行起来，但一直停留在加载动画那里

浏览器控制台输出：

```
GET http://127.0.0.1:8080/account/info ==>> Failed to load http://127.0.0.1:8080/account/info
```

- 原因：未修改`rap2-delos/src/config`目录下服务端连接地址, 或者修改结果与 [rap2-dolores](https://github.com/thx/rap2-dolores) 实际提供服务地址不匹配
- 解决方法：修改`config.dev.ts`文件 serve 配置信息

> 如果 Windows 系统修改正确无误后，依旧出错，那么查看 hosts(路径：C:\Windows\System32\drivers\etc) 中 127.0.0.1 的 IP 前是否有`#`，如果有请取消注释

#### MySQL 运行问题

##### 错误一

![](https://res.cloudinary.com/incoder/image/upload/v1525517475/blog/gitpages-rap2-mysql.png)

- 原因：MySQL 集成命令没有加入系统的环境变量
- 解决方法：将安装的 MySQL Service 路径加入系统变量

![](https://res.cloudinary.com/incoder/image/upload/v1525517495/blog/gitpages-rap2-mysql-path.png)

##### 错误二

![](https://res.cloudinary.com/incoder/image/upload/v1525517523/blog/gitpages-rap2-mysql-create.png)

- 原因：没有数据库链接权限
- 解决方法：先登录用 root 数据库，密码具体看自己数据库当时设置的密码

## 三、如何获取更新

目前请选择`master`分支源码，后续其他分支请看相应分支说明文档。在开发环境中git pull来获取最新的源码更新，每一期更新都会有对应的update.md请关注并按照上面的指示进行升级工作。

**Comment by youngjuning** [comment]
## 二、客户端 dolores 环境搭建

### 2.1、获取源代码

```bash
$ git clone https://github.com/thx/rap2-dolores.git
```

### 2.2、安装项目依赖包

```bash
$ npm install # 项目根目录
```

### 2.3、环境配置

修改`rap2-dolores/src/config/config.dev.ts`文件，`serve`地址是 **服务端** `rap2-delos` 部署成功后的地址，默认：`'http://localhost:8080'`

### 2.3、启动项目

#### 开发模式

自动监视改变后重新编译

```bash
$ npm run dev
```

#### 测试用例

```bash
$ npm run test
```

#### 生产模式

编译 React 生产包

```bash
$ npm run build
```

用 serve 命令或 nginx 服务器路由到编译产出的 build 文件夹作为静态服务器即可

```bash
serve -s ./build -p 7070
```

看到浏览器中出现登录页面，表示部署成功

![](https://res.cloudinary.com/incoder/image/upload/v1525517454/blog/gitpages-rap2-dolores-success.png)

### 2.4 常见问题

#### 部署问题

##### 1、执行`npm run dev`，提示

```bash
return process.dlopen(module,path._makeLong(filename))
...
...node_modules\node-sass\vendor\win32-x64-57\binding.node is not a valid Win32 application...
```

- 原因：项目依赖包`node-sass`没有安装完全
- 解决方法：`npm install node-sass`

##### 2、项目运行起来，但一直停留在加载动画那里

浏览器控制台输出：

```
GET http://127.0.0.1:8080/account/info ==>> Failed to load http://127.0.0.1:8080/account/info
```

- 原因：未修改`rap2-delos/src/config`目录下服务端连接地址, 或者修改结果与 [rap2-dolores](https://github.com/thx/rap2-dolores) 实际提供服务地址不匹配
- 解决方法：修改`config.dev.ts`文件 serve 配置信息

> 如果 Windows 系统修改正确无误后，依旧出错，那么查看 hosts(路径：C:\Windows\System32\drivers\etc) 中 127.0.0.1 的 IP 前是否有`#`，如果有请取消注释

#### MySQL 运行问题

##### 错误一

![](https://res.cloudinary.com/incoder/image/upload/v1525517475/blog/gitpages-rap2-mysql.png)

- 原因：MySQL 集成命令没有加入系统的环境变量
- 解决方法：将安装的 MySQL Service 路径加入系统变量

![](https://res.cloudinary.com/incoder/image/upload/v1525517495/blog/gitpages-rap2-mysql-path.png)

##### 错误二

![](https://res.cloudinary.com/incoder/image/upload/v1525517523/blog/gitpages-rap2-mysql-create.png)

- 原因：没有数据库链接权限
- 解决方法：先登录用 root 数据库，密码具体看自己数据库当时设置的密码

## 三、如何获取更新

目前请选择`master`分支源码，后续其他分支请看相应分支说明文档。在开发环境中git pull来获取最新的源码更新，每一期更新都会有对应的update.md请关注并按照上面的指示进行升级工作。

## 参考链接

#### 官方

- [RAP2文档](https://github.com/thx/rap2-delos/wiki)
- [rap2-delos](https://github.com/thx/rap2-delos)：后端数据API服务器，基于Koa + MySQL
- [rap2-dolores](http://t.cn/E2BRYXT)：前端静态资源，基于React

### rap2部署

- [Api 文档管理系统 RAP2 环境搭建](http://t.cn/E2B89RX)
- [rap2服务端 delos部署](http://t.cn/E7Gu9wv)
- [RAP2搭建教程(mock服务)](http://www.195440.com/?p=586)
- [教你使用docker部署淘宝rap2镜像](http://t.cn/E2RfWcE)
- [RAP2：使用docker镜像进行构建，启动部署](http://t.cn/E2RfspZ)
- [Docker部署手册](http://t.cn/E2BRcCW)

### Redis

- [redis如何后台启动](http://t.cn/E2BQykv)

- [Redis 配置文件介绍](http://t.cn/E2BQTi0)

#### 进程管理

- [PM2实用入门指南](http://t.cn/E2B84d3)

**Comment by youngjunning** [comment]
# Docker 部署

## 一、前提

> 请确定你的平台来选择

- 安装docker及docker-compose
  - [树莓派](https://github.com/youngjuning/youngjuning.github.io/issues/190#issuecomment-440901101)
  - [其他](http://t.cn/RosKYqj)

## 二、后端部署

### 2.1、获取源码

```sh
$ git clone https://github.com/thx/rap2-delos.git
```

### 2.2、修改默认配置

### 2.3、通过源码运行

```sh
$ docker-compose up -d
```

### 2.4、第一次运行需要手动初始化mysql数据库。分别执行以下命令：
   
```sh
$ docker exec -it rap2-delos sh
# 登录成功以后执行：
$ node scripts/init
# 执行完毕后退出
$ exit
# 如果仍然有问题，重新启动
$ docker-compose down
# 重新运行
$ docker-compose up -d
```

## 三、前端部署

### clone rap2-doloers-docker

```sh
$ git clone https://github.com/youngjuning/rap2-dolores-docker
```

### 配置

更改 `src/config/config.prod.js` 中的配置，将接口请求地址指向你的后端服务器，以下是我的配置，各位按需更改。

```js
module.exports = {
  serve: 'http://127.0.0.1:38080',
  keys: ['some secret hurr'],
  session: {
    key: 'koa:sess'
  }
}
```

### 启动服务

```sh
$ docker-compose up -d
```

#198

**Comment by youngjunning** [comment]
## 参考链接

#### 官方

- [RAP2文档](https://github.com/thx/rap2-delos/wiki)
- [rap2-delos](https://github.com/thx/rap2-delos)：后端数据API服务器，基于Koa + MySQL
- [rap2-dolores](http://t.cn/E2BRYXT)：前端静态资源，基于React

### rap2部署

- [Api 文档管理系统 RAP2 环境搭建](http://t.cn/E2B89RX)
- [rap2服务端 delos部署](http://t.cn/E7Gu9wv)
- [RAP2搭建教程(mock服务)](http://www.195440.com/?p=586)
- [教你使用docker部署淘宝rap2镜像](http://t.cn/E2RfWcE)
- [Docker部署手册](http://t.cn/E2BRcCW)

### Redis

- [redis如何后台启动](http://t.cn/E2BQykv)

- [Redis 配置文件介绍](http://t.cn/E2BQTi0)

#### 进程管理

- [PM2实用入门指南](http://t.cn/E2B84d3)

**Comment by youngjunning** [comment]
- [mock入门指北](#189)

**Comment by youngjunning** [comment]
## 使用教程

### 清空测试数据

> 坑：rap2 `npm run create-db` 创建的测试账号是明文密码，但其实登录校验是要两次md5加密的。
> 解决办法是用 https://md5jiami.51240.com/ 对你想要的明文密码两次**小32**加密，然后分别填入 admin 和 墨智的密码中（我用的navicat premium）

1. 清空 admin 账号添加的数据
2. 清空 墨智 添加的数据
3. 删除测试账号

**Comment by youngjunning** [comment]
#192
