### ISSUE TITLE
Yapi - 顶尖 API 文档管理工具

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#201]
## Yapi

> yapi [![GitHub stars](https://img.shields.io/github/stars/YMFE/yapi.svg?style=social&label=Stars)](https://github.com/YMFE/yapi) :YApi 是一个可本地部署的、打通前后端及QA的、可视化的接口管理平台

> 在线体验：http://yapi.demo.qunar.com/

## 平台介绍

![image](https://user-images.githubusercontent.com/13204332/48997484-18958380-f18b-11e8-9c1f-77b3ebe949d1.png)

YApi 是高效、易用、功能强大的 api 管理平台，旨在为开发、产品、测试人员提供更优雅的接口管理服务。可以帮助开发者轻松创建、发布、维护 API，YApi 还为用户提供了优秀的交互体验，开发人员只需利用平台提供的接口数据写入工具以及简单的点击操作就可以实现接口的管理。

### 特性

1. 基于 Json5 和 Mockjs 定义接口返回数据的结构和文档，效率提升多倍
2. 扁平化权限设计，即保证了大型企业级项目的管理，又保证了易用性
3. 类似 postman 的接口调试
4. 自动化测试, 支持对 Response 断言
5. MockServer 除支持普通的随机 mock 外，还增加了 Mock 期望功能，根据设置的请求过滤规则，返回期望数据
6. 支持 postman, har, swagger 数据导入
7. 免费开源，内网部署，信息再也不怕泄露了

## [YMFE](https://ymfe.org/)

去哪儿网大前端技术中心（YMFE）

去哪儿网大前端技术中心（YMFE）是由FE，iOS和Android工程师共同组成的，去哪儿最具想象力、创造力和影响力的大前端团队

## 参考资源

- [官方文档](https://yapi.ymfe.org/index.html)
- [anoy/yapi](http://t.cn/ELt0NmL):使用 Docker 构建 Yapi(麻烦，没有使用docker-compose)
- [branchzero/yapi](https://hub.docker.com/r/branchzero/yapi/):yapi docker for https://github.com/YMFE/yapi (使用docker-compose管理)
- [顶尖 API 文档管理工具 (Yapi)](https://anoyi.com/p/a97d2efb23c5)
- [阿里容器镜像服务](https://dev.aliyun.com/)：高性能的本地Registry，提供上传、下载、构建及托管的全方位镜像服务
- [构建yapi容器,从构建发布到可用](http://t.cn/EvRAXtN)

**Comment by youngjunning** [comment]
## 使用 Docker 构建 Yapi

### 1、创建 MongoDB 数据卷

```sh
$ docker volume create mongo_data_yapi
```

### 2、启动 MongoDB

**正常CPU架构**

```sh
$ docker run -p 27017:27017 -d --name mongo-yapi -v mongo_data_yapi:/data/db mongo
```

**树莓派**

```sh
$ docker run -p 27017:27017 -d --name mongo-yapi -v mongo_data_yapi:/data/db andresvidal/rpi3-mongodb3 # 树莓派
```

### 3、获取 Yapi 镜像，版本信息可在 阿里云镜像仓库 查看

```sh
$ docker pull registry.cn-hangzhou.aliyuncs.com/anoy/yapi
```

### 4、初始化 Yapi 数据库索引及管理员账号

> 初始化管理员账号成功,默认账号名：`admin@admin.com`，密码：`ymfe.org`

```sh
$ docker run -it --rm --link mongo-yapi:mongo --entrypoint npm --workdir /api/vendors registry.cn-hangzhou.aliyuncs.com/anoy/yapi run install-server 
```

**树莓派**

> 树莓派只能用来作为学习用，哈哈，如果有钱，还是买一个家用服务器吧！！！

```sh
$ docker run -it --rm --link mongo-yapi:andresvidal/rpi3-mongodb3 --entrypoint npm --workdir /api/vendors andresvidal/rpi3-mongodb3 run install-server 
```

自定义配置文件挂载到目录 `/api/config.json`，官方自定义配置文件 -> [传送门](https://github.com/YMFE/yapi/blob/master/config_example.json)

5、启动 Yapi 服务

```sh
docker run -d --name yapi --link mongo-yapi:mongo --workdir /api/vendors -p 3000:3000 registry.cn-hangzhou.aliyuncs.com/anoy/yapi server/app.js -v yapi:/api/vendors
```

> 详细参考：http://t.cn/ELt0NmL

**Comment by youngjunning** [comment]
```sh
$ docker exec -it yapi sh
```

**Comment by youngxiaoran** [comment]
## 使用 Docker 构建 Yapi

### 1、创建 MongoDB 数据卷

```sh
$ docker volume create mongo_data_yapi
```

### 2、启动 MongoDB

**正常CPU架构**

```sh
$ docker run -p 27017:27017 -d --name mongo-yapi -v mongo_data_yapi:/data/db mongo
```

**树莓派**

```sh
$ docker run -p 27017:27017 -d --name mongo-yapi -v mongo_data_yapi:/data/db andresvidal/rpi3-mongodb3 # 树莓派
```

### 3、获取 Yapi 镜像，版本信息可在 阿里云镜像仓库 查看

```sh
$ docker pull registry.cn-hangzhou.aliyuncs.com/anoy/yapi
```

### 4、初始化 Yapi 数据库索引及管理员账号

> 初始化管理员账号成功,默认账号名：`admin@admin.com`，密码：`ymfe.org`

```sh
$ docker run -it --rm --link mongo-yapi:mongo --entrypoint npm --workdir /api/vendors registry.cn-hangzhou.aliyuncs.com/anoy/yapi run install-server 
```

**树莓派**

> 树莓派只能用来作为学习用，哈哈，如果有钱，还是买一个家用服务器吧！！！

```sh
$ docker run -it --rm --link mongo-yapi:andresvidal/rpi3-mongodb3 --entrypoint npm --workdir /api/vendors andresvidal/rpi3-mongodb3 run install-server 
```

自定义配置文件挂载到目录 `/api/config.json`，官方自定义配置文件 -> [传送门](https://github.com/YMFE/yapi/blob/master/config_example.json)

5、启动 Yapi 服务

```sh
docker run -d --name yapi --link mongo-yapi:mongo --workdir /api/vendors -p 3000:3000 registry.cn-hangzhou.aliyuncs.com/anoy/yapi server/app.js -v yapi:/api/vendors
```

> 详细参考：http://t.cn/ELt0NmL
