### ISSUE TITLE
js事件处理机制是啥

### ISSUE THREAD

**Issue by baijiezhen** [youngjunning/issues#3]
这个命题比较大，大家可以自由发挥，推荐大家原创，但是也可以引用网络资源

**Comment by youngjunning** [comment]
## 什么是事件

事件(Event)是 `JavaScript` 应用跳动的心脏 ，也是把所有东西粘在一起的胶水。当我们与浏览器中 Web 页面进行某些类型的交互时，事件就发生了。事件可能是用户在某些内容上的点击、鼠标经过某个特定元素或按下键盘上的某些按键。事件还可能是 Web 浏览器中发生的事情，比如说某个 Web 页面加载完成，或者是用户滚动窗口或改变窗口大小。

通过使用 `JavaScript` ，你可以监听特定事件的发生，并规定让某些事件发生以对这些事件做出响应。

**Comment by youngjunning** [comment]
@baijiezhen [JavaScript中的事件处理机制 - 简书](http://t.cn/RuKKPgF) 可以瞅瞅这个，写的不错
