### ISSUE TITLE
JavaScript、jQuery、Nodejs库收藏

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#7]
本文收藏的是 javascript、nodejs、jquery等非框架的插件。因为有时一个库可能有这三种环境的版本

**Comment by youngjunning** [comment]
## 灯箱

- fancyapps/fancybox [![GitHub stars](https://img.shields.io/github/stars/fancyapps/fancybox.svg?style=social&label=Stars)](https://github.com/fancyapps/fancybox)：jQuery lightbox script for displaying images, videos and more. Touch enabled, responsive and fully customizable.

**Comment by youngjunning** [comment]
## 雪花特效

- scottschiller/snowstorm [![GitHub stars](https://img.shields.io/github/stars/scottschiller/snowstorm.svg?style=social&label=Stars)](https://github.com/scottschiller/snowstorm/)：Enterprise-grade JavaScript snow effect for the internets, setting CPUs on fire worldwide every winter since 2003.
- loktar00/JQuery-Snowfall [![GitHub stars](https://img.shields.io/github/stars/loktar00/JQuery-Snowfall.svg?style=social&label=Stars)](https://github.com/loktar00/JQuery-Snowfall)：Makes it snow on any web page or specific element.

**Comment by youngjunning** [comment]
## 时间处理

- iamkun/dayjs [![GitHub stars](https://img.shields.io/github/stars/iamkun/dayjs.svg?style=social&label=Stars)](https://github.com/iamkun/dayjs)：Day.js 2KB是替代Moment.js的不可变的日期库，具有相同的现代API

**Comment by youngjunning** [comment]
## 表格插件

- DataTables/DataTables [![GitHub stars](https://img.shields.io/github/stars/DataTables/DataTables.svg?style=social&label=Stars)](https://github.com/DataTables/DataTables)：Tables plug-in for jQuery

**Comment by youngjunning** [comment]
## Marquee

- aamirafridi/jQuery.Marquee [![GitHub stars](https://img.shields.io/github/stars/aamirafridi/jQuery.Marquee.svg?style=social&label=Stars)](https://github.com/aamirafridi/jQuery.Marquee)：jQuery plugin to scroll the text like the old traditional marquee

**Comment by youngjuning** [comment]
## Mock

1. typicode/json-server [![GitHub stars](https://img.shields.io/github/stars/typicode/json-server.svg?style=social&label=Stars)](https://github.com/typicode/json-server)：零代码，30S快速伪造后端接口
2. nuysoft/Mock [![GitHub stars](https://img.shields.io/github/stars/nuysoft/Mock.svg?style=social&label=Stars)](https://github.com/nuysoft/Mock)：生成随机数据，拦截 Ajax 请求
3. easy-mock/easy-mock [![GitHub stars](https://img.shields.io/github/stars/easy-mock/easy-mock.svg?style=social&label=Stars)](https://github.com/easy-mock/easy-mock)：一个可视化，并且能快速生成模拟数据的持久化服务

**Comment by youngjuning** [comment]
## API文档

1. TommyLemon/APIJSON [![GitHub stars](https://img.shields.io/github/stars/TommyLemon/APIJSON.svg?style=social&label=Stars)](https://github.com/TommyLemon/APIJSON)：⚡后端接口和文档自动化，前端(客户端) 定制返回JSON的数据和结构！ 
2. https://github.com/swagger-api ：一款写swagger的工具，学习成本高，慎用
3. https://github.com/apiaryio/api-blueprint ： 支持 markdown

**Comment by youngjunning** [comment]
## 图片处理

- photopea/UPNG.js [![GitHub stars](https://img.shields.io/github/stars/photopea/UPNG.js.svg?style=social&label=Stars)](https://github.com/photopea/UPNG.js)：Fast and advanced PNG (APNG) decoder and encoder (lossy / lossless)

**Comment by youngjunning** [comment]
## MD5

- https://github.com/crypto-browserify/md5.js
- https://github.com/jifeng/node-md5
- https://github.com/blueimp/JavaScript-MD5
