### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#88]
### Nodejs下载地址

Nodejs中文官网：https://nodejs.org/zh-cn/

### Nodejs目录

`node_modules` 目录是默认的全局模块的存储路径。nodejs默认安装的模块只有npm，npm模块用来安装其他nodejs模块。下面是默认的安装目录（高版本可能不同）：

![image](https://user-images.githubusercontent.com/13204332/41081855-e5cb6f4a-6a5e-11e8-91c9-2b75083128d7.png)

### Nodejs默认全局环境

- npm的全局安装包位置：`C:\Users\youngjuning\AppData\Roaming\npm`
- npm的全局cache位置：`C:\Users\youngjuning\AppData\Roaming\npm-cache`

**Comment by youngjunning** [comment]
## NPM版本维护

### 下载最新npm

```bash
$ npm install npm@latest -g
```

再次开启 `cmd` 命令行，进入 `node` ，输入 `require('npm')` 来测试下 `node` 的模块全局路径是否配置正确了。正确的话 `cmd` 会列出 `express` 的相关信息。如出错一般都是 `NODE_PATH` 的配置不对。

**Comment by youngjunning** [comment]
## 代理管理

> 两种方案任选一种

### nrm管理registry

- [nrm](https://github.com/Pana/nrm)： NPM registry 管理工具

### 更换淘宝源

> 网址：http://npm.taobao.org/ 
> 注意：淘宝源无法使用 `npm search` 命令

打开nodejs客户端，输入一下命令：

```bash
$ npm config set registry http://registry.npm.taobao.org
$ npm info underscore （如果上面配置正确这个命令会有字符串返回）
$ npm config set disurl https://npm.taobao.org/dist
```

另外我们也可以用命令行指定：

```bash
$ npm –registry http://registry.cnpmjs.org info underscore
# 配置后可通过下面方式来验证是否成功
$ npm config get registry
```

**Comment by youngjunning** [comment]
## GNVM管理Noejs版本

- Github：https://github.com/Kenshin/gnvm
- 官网：http://ksria.com/gnvm/

**Comment by youngjuning** [comment]
## nrm管理registry

- [nrm](https://github.com/Pana/nrm)： NPM registry 管理工具

**Comment by youngjunning** [comment]
## 不占用C盘的设置

> 建议开发机的C盘100G空间。其他软件无所谓，但是开发用软件的依赖还是默认C盘最稳定

### 配置prefix和cache

nodejs安装成功后第一件事是配置全局模块的存储路径和Cache文件的存储路径。在nodejs安装目录下新建node_cache和node_global两个文件夹。如下：

![image](https://user-images.githubusercontent.com/13204332/41081826-d8167304-6a5e-11e8-897f-c1d321086fda.png)

```bash
#在CMD命令行输入：
$ npm config set prefix "C:\Program Files\nodejs\node_global"
$ npm config set cache "C:\Program Files\nodejs\node_cache"
```

也可以直接编辑我的文档下的.npmrc文件写入，建议备份一下，留作以后用：

```bash
prefix=D:\Program Files\nodejs\node_global
cache=D:\Program Files\nodejs\node_cache
```
### 环境变量设置

#### 配置路径

```shell
"我的电脑"—>右键—>"属性"—>"高级系统设置"—>"环境变量"
```

| 键           | 值                                               |
| ------------ | ------------------------------------------------ |
| NODE_PATH    | D:\Program Files\nodejs\node_global\node_modules |
| 系统变量PATH | D:\ProgramFiles\nodejs\node_global\              |
| 系统变量PATH | D:\ProgramFiles\nodejs\                          |
| 用户变量PATH | D:\ProgramFiles\nodejs\node_global\              |
| 用户变量PATH | D:\ProgramFiles\nodejs\                          |

**Comment by youngjunning** [comment]
## ndb 调试 node

- GoogleChromeLabs/ndb [![GitHub stars](https://img.shields.io/github/stars/GoogleChromeLabs/ndb.svg?style=social&label=Stars)](https://github.com/GoogleChromeLabs/ndb)：ndb is an improved debugging experience for Node.js, enabled by Chrome DevTools

**Comment by youngjunning** [comment]
## nodejs 守护进程

- foreverjs/forever [![GitHub stars](https://img.shields.io/github/stars/foreverjs/forever.svg?style=social&label=Stars)](https://github.com/foreverjs/forever)：forever是一个简单的命令式nodejs的守护进程，能够启动，停止，重启App应用
- Unitech/pm2 [![GitHub stars](https://img.shields.io/github/stars/Unitech/pm2.svg?style=social&label=Stars)](https://github.com/Unitech/pm2)：Node.js Production Process Manager with a built-in Load Balancer.

**Comment by youngjunning** [comment]
## nodejs 开发工具

- remy/nodemon [![GitHub stars](https://img.shields.io/github/stars/remy/nodemon.svg?style=social&label=Stars)](https://github.com/remy/nodemon)：nodemon用来监视node.js应用程序中的任何更改并自动重启服务,非常适合用在开发环境中。

**Comment by youngjunning** [comment]
## react-native

- rnpm/rnpm [![GitHub stars](https://img.shields.io/github/stars/rnpm/rnpm.svg?style=social&label=Stars)](https://github.com/rnpm/rnpm):📱 React Native Package Manager

**Comment by youngjunning** [comment]
## yarn

- huangyanxiong01/yrs [![GitHub stars](https://img.shields.io/github/stars/huangyanxiong01/yrs.svg?style=social&label=Stars)](https://github.com/huangyanxiong01/yrs)：Yarn registry switch tool

**Comment by youngjunning** [comment]
## 加快下载速度

### electron

```bash
$ export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
```

或者参考 https://www.jianshu.com/p/568db76a7b45

### node-sass

```bash
$ export SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"
```

或者参考 https://www.jianshu.com/p/ce28d103671f

**Comment by youngjunning** [comment]
## n - 以交互方式管理您的Node.js版本

### 安装/激活版本

执行 `n <version>` 来下载指定版本的。如果`<version>` 已经通过 `n` 下载过了。`n` 将激活那个版本。

```sh
$ n 0.8.14
$ n 0.8.17
$ n 0.9.6
```

执行 `n` 命令查看已经安装的node版本。用 `up` 和 `down` 键来选择版本，用 `right` 键来选择。使用 `^C(control + c)` 退出。

```sh
$ n
```

```
0.8.14
ο 0.8.17
  0.9.6
```

Use or install the latest official release:

```sh
$ n latest
```

Use or install the stable official release:

```sh
$ n stable
```

Use or install the latest LTS official release:

```sh
$ n lts
```

### 删除版本

删除部分版本:

```sh
$ n rm 0.9.4 v0.10.0
```

> 可选的,你可以使用 `-` 代替 `rm`: `$ n - 0.9.4`

除了当前使用的版本，删除所有版本：

```sh
$ n prune
```

**Comment by youngjunning** [comment]
## npm发布以@开头命名的public公有包

> 官方教程：https://docs.npmjs.com/creating-and-publishing-an-org-scoped-package

![image](https://user-images.githubusercontent.com/13204332/49054330-d4f45580-f22e-11e8-8775-ea6d361870da.png)

真相只有一个，原来是发布命令有问题！！！应该是只能发布public公有的包，否则得认证之类的。后面有机会再研究。

```sh
$ npm publish --access public
```
