### ISSUE TITLE
ReactNative简明环境搭建之Android

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#89]
## 必需的软件

> React Native 中文网推荐的是 Chocolatey，但是这个东西使用起来并没有预期的那么方便，我在这里把需要的资源都准备好了

### Python

下载解压并安装即可，[python-2.7.14.amd64.zip](https://github.com/youngjuning/issue-blog/files/2079141/python-2.7.14.amd64.zip)

### NodeJS

参考NodeJS开发环境维护#88 

### Yarn、React Native的命令行工具（react-native-cli）

`npm install -g yarn react-native-cli`

### Android Studio

这个参考中文网的就可以：https://reactnative.cn/docs/0.51/getting-started.html#android-studio

> 安装中的坑详见：Android Studio 安装的坑 #67

### Gradle Daemon

开启Gradle Daemon可以极大地提升java代码的增量编译速度。

> 命令行执行以下命令

```bash
(if not exist "%USERPROFILE%/.gradle" mkdir "%USERPROFILE%/.gradle") && (echo org.gradle.daemon=true >> "%USERPROFILE%/.gradle/gradle.properties")
```

### 将Android SDK的Tools目录添加到 `PATH` 变量中

你可以把 Android SDK 的 tools 和 platform-tools 目录添加到 `PATH` 变量中，以便在终端中运行一些Android工具，例如 `android avd` 或是 `adb logcat` 等。

打开 `控制面板` -> `系统和安全` -> `系统` -> `高级系统设置` ->` 高级` -> `环境变量` -> `选中PATH` -> 双击进行编辑

注意你的具体路径可能和下图不同

![image](https://user-images.githubusercontent.com/13204332/41085296-2645d902-6a69-11e8-89ab-89b2ae28cb4e.png)

**Comment by youngjunning** [comment]
## 模拟器

- Android Studio自带的模拟器
- [Genymotion](https://www.genymotion.com/)：只对个人免费
- [夜神模拟器](https://www.yeshen.com/)：Android SDK 版本太低
- [网易MUMU](http://mumu.163.com/)：博主用的这个
- Visual Studio Emulator for Android

**Comment by youngjunning** [comment]
## 开始第一个项目

### 脚手架安装项目

```bash
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```

### 真机上模拟

你需要开启USB调试才能在你的设备上安装你的APP。首先，确定[你已经打开设备的USB调试开关](http://t.cn/R1ko3TV)，博主的是[oppo r9 plus](http://t.cn/R1koFD2)

确保你的设备已经成功连接。可以输入 `adb devices` 来查看:

![image](https://user-images.githubusercontent.com/13204332/41090458-dfd85a54-6a76-11e8-9272-dc37069c33b9.png)

在右边那列看到 `device` 说明你的设备已经被正确连接了。

> 注意，你只应当连接仅仅一个设备。

> 译注：如果你连接了多个设备（包含模拟器在内），后续的一些操作可能会失败。拔掉不需要的设备，或者关掉模拟器，确保adb devices的输出只有一个是连接状态。

> 译注：在真机上运行时可能会遇到白屏的情况，请找到并开启[悬浮窗权限](http://t.cn/R1kN2jr)。

> 关于 release 和 debug
> 你还可以运行react-native run-android --variant=release来安装release版的应用。当然你需要先配置好> 签名，且此时无法再开启开发者菜单。注意在debug和release版本间来回切换安装时可能会报错签名不> 匹配，此时需要先卸载前一个版本再尝试安装。

### 从设备上访问开发服务器

在启用开发服务器的情况下，你可以快速的迭代修改应用，然后在设备上查看结果。按照下面描述的任意一种方法来使你的运行在电脑上的开发服务器可以从设备上访问到。

> 注意
> 大部分现代的安卓设备已经没有了硬件"Menu"按键，这是我们用来调出开发者菜单的。在这种情况下
> 你可以通过摇晃设备来打开开发者菜单(重新加载、调试，等等……)

#### (Android 5.0及以上)使用adb reverse命令

> 注意，这个选项只能在5.0以上版本(API 21+)的安卓设备上使用。

首先把你的设备通过USB数据线连接到电脑上，并开启USB调试（关于如何开启USB调试，参见上面的章节）。

1. 运行 `adb reverse tcp:8081 tcp:8081`
2. 不需要更多配置，你就可以使用 `Reload JS` 和其它的开发选项了。

#### (Android 5.0以下)通过Wi-Fi连接你的本地开发服务器

1. 首先确保你的电脑和手机设备在同一个 **Wi-Fi环境** 下。
2. 在设备上运行你的React Native应用。和打开其它App一样操作。
3. 你应该会看到一个“红屏”错误提示。这是正常的，下面的步骤会解决这个报错。
4. 摇晃设备，或者运行 `adb shell input keyevent 82`，可以打开**开发者菜单**。
5. 点击进入 `Dev Settings`。
6. 点击 `Debug server host for device`。
7. 输入你电脑的IP地址和端口号（譬如10.0.1.1:8081）。在Mac上，你可以在系统设置/网络里找查询你的IP地址。在Windows上，打开命令提示符并输入 `ipconfig` 来查询你的IP地址。在Linux上你可以在终端中输入 `ifconfig` 来查询你的IP地址。
8. 回到 `开发者菜单` 然后选择Reload JS。

### 真机预览的各种坑

1. 建议安装完 android studio 之后先打开更新一下andorid studio
2. 第一次执行 `react-native run-android` 会下载相应版本的 gradle，这个比较慢，最好翻墙或者从其他已经下好的拷一个过来

**Comment by youngjuning** [comment]
## JDK 1.8

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by youngjunning** [comment]
```bash
$ adb forward tcp:8082 tcp:8082
$ adb forward tcp:8083 tcp:8083
```

**Comment by youngxiaoran** [comment]
```
adb reverse tcp:8081 tcp:8081
```
